//
//  NotificationScheduleParityTests.swift
//  RedCalendar-FemaleTests
//

import XCTest
@testable import RedCalendar_Female

/// SYNC.md §20.2 — that the days the server schedules notifications for are the days this
/// calendar draws.
///
/// The server predicts the next period start, ovulation and period end from the last marked
/// cycle and the three numbers in `settings.cycle`, and it does so in its own repository, in
/// JavaScript, against a database this app never sees. Nothing links the two implementations but
/// the rule being written down twice. A prediction that drifts apart is invisible from both
/// sides: the server logs a notification it considers correct, the app draws a calendar it
/// considers correct, and the only place the disagreement surfaces is a lock screen saying
/// "period in 2 days" over a calendar that says something else.
///
/// What §20.2 actually promises is that the **series** coincides, not that a particular row and
/// a particular pixel do. The server's row may hold a step behind the calendar's next drawn
/// start — deliberately, so an event it has not spoken about yet is not skipped — but the day it
/// names is always a day of the same arithmetic series, so the text picked from the difference
/// at send time still describes what the calendar shows. So that is what is asserted here: for
/// every occurrence the server could ever name, this app draws that day as that event.
///
/// The numbers in `Case` were generated by running the server's own
/// `services/notification-schedule.js` over the same cases, not derived by hand from the prose.
///
/// Its counterpart is `app/test/notification-schedule.test.js` in `redcalendar-api`, which runs
/// the same table against the server. Change the rule on either side and one of the two fails.
final class NotificationScheduleParityTests: XCTestCase {

    /// 2026-09-02, the day the rest of the notification tests are written around. Nothing here
    /// depends on the value; every expectation is a distance from the anchor.
    private static let today = Daystamp(rawValue: 9375)

    /// How far out the server's series is followed. Five is past anything a reader reaches
    /// without opening the app — the point of the multiple-of-the-length rule is that the
    /// schedule never runs dry (§20.2) — and short enough to keep the loaded range honest.
    private static let occurrences = 1...5

    // MARK: - The table

    private struct Case {
        let name: String
        let anchorDaysAgo: Int
        let openPeriod: Bool
        let ovulation: OvulationData?
        let cycleLength: Int
        let periodLength: Int
        let lutealPhase: Int
    }

    private static let cases: [Case] = [
        // The anchor is a marked start, so the first predicted one is a whole cycle later, never
        // today: that is the `max(1, …)` in §20.2.
        Case(name: "marked today", anchorDaysAgo: 0, openPeriod: false, ovulation: nil,
             cycleLength: 28, periodLength: 5, lutealPhase: 14),
        Case(name: "ten days in", anchorDaysAgo: 10, openPeriod: false, ovulation: nil,
             cycleLength: 28, periodLength: 5, lutealPhase: 14),
        // Either side of the predicted start, where a `ceil` and a `floor` part company.
        Case(name: "the day before the predicted start", anchorDaysAgo: 27, openPeriod: false,
             ovulation: nil, cycleLength: 28, periodLength: 5, lutealPhase: 14),
        Case(name: "on the predicted start", anchorDaysAgo: 28, openPeriod: false, ovulation: nil,
             cycleLength: 28, periodLength: 5, lutealPhase: 14),
        // Three cycles with nothing marked — the case the whole multiple-of-the-length rule
        // exists for.
        Case(name: "three cycles unmarked", anchorDaysAgo: 100, openPeriod: false, ovulation: nil,
             cycleLength: 28, periodLength: 5, lutealPhase: 14),
        Case(name: "open period", anchorDaysAgo: 3, openPeriod: true, ovulation: nil,
             cycleLength: 28, periodLength: 5, lutealPhase: 14),
        Case(name: "open period, well past its forecast", anchorDaysAgo: 10, openPeriod: true,
             ovulation: nil, cycleLength: 28, periodLength: 5, lutealPhase: 14),
        Case(name: "settings of her own", anchorDaysAgo: 10, openPeriod: false, ovulation: nil,
             cycleLength: 26, periodLength: 6, lutealPhase: 12),
        // The luteal phase at its ceiling against a short cycle, where the two clamps in
        // ResolvedCycleSettings intersect.
        Case(name: "short cycle, long luteal phase", anchorDaysAgo: 5, openPeriod: false,
             ovulation: nil, cycleLength: 21, periodLength: 3, lutealPhase: 20),
        Case(name: "long cycle", anchorDaysAgo: 40, openPeriod: false, ovulation: nil,
             cycleLength: 35, periodLength: 7, lutealPhase: 16),
    ]

    // MARK: - §20.2, the series

    /// Every start the server can name is drawn here as the start of a predicted period.
    func testEveryPredictedStartInTheSeriesIsDrawn() {
        for testCase in Self.cases {
            let drawn = states(for: testCase)
            for k in Self.occurrences {
                let day = anchor(testCase) + k * testCase.cycleLength
                assertPeriod(drawn[day], caps: [.start, .single],
                             "\(testCase.name): start #\(k)")
            }
        }
    }

    /// And the last day of each of those periods is drawn as the end of the bar — the `- 1` in
    /// §20.2, which is the rule this app draws by (`CycleRecord.periodCoverage`) and which cost
    /// a whole kind of notification a day of accuracy when the server was missing it.
    func testEveryPredictedEndInTheSeriesIsDrawn() {
        for testCase in Self.cases {
            let drawn = states(for: testCase)
            for k in Self.occurrences {
                let start = anchor(testCase) + k * testCase.cycleLength
                let day = start + testCase.periodLength - 1
                assertPeriod(drawn[day], caps: [.end, .single], "\(testCase.name): end #\(k)")
            }
        }
    }

    /// And each of those cycles' ovulation is drawn a luteal phase before its start.
    func testEveryPredictedOvulationInTheSeriesIsDrawn() {
        for testCase in Self.cases {
            let drawn = states(for: testCase)
            for k in Self.occurrences {
                let day = anchor(testCase) + k * testCase.cycleLength - testCase.lutealPhase
                assertOvulation(drawn[day], "\(testCase.name): ovulation #\(k)")
            }
        }
    }

    /// The open period is the one end that is not a member of the series: it is counted from the
    /// day she marked rather than from the predicted start, because a period that is running has
    /// an end to remind her about now and not in a month (§20.2).
    func testTheEndOfAnOpenPeriodIsCountedFromTheMarkedStart() {
        for testCase in Self.cases where testCase.openPeriod {
            let drawn = states(for: testCase)
            let day = anchor(testCase) + testCase.periodLength - 1
            assertPeriod(drawn[day], caps: [.end, .single], "\(testCase.name): open end")
        }
    }

    // MARK: - §20.2, the occurrence an answer takes out

    /// A confirmed day replaces the first ovulation of the series on the calendar, and that is
    /// the whole reason the schedule skips that occurrence rather than announcing it: the
    /// formula's day is no longer drawn as an ovulation at all, so a notification about it would
    /// name a day the calendar has moved off.
    func testAConfirmedDayReplacesTheFirstOvulationOfTheSeries() {
        let testCase = Case(name: "confirmed", anchorDaysAgo: 10, openPeriod: false,
                            ovulation: .confirmed(day: Daystamp(rawValue: 9375 - 6)),
                            cycleLength: 28, periodLength: 5, lutealPhase: 14)
        let drawn = states(for: testCase)
        let start = anchor(testCase)

        assertOvulation(drawn[Daystamp(rawValue: 9375 - 6)], "the confirmed day is drawn")

        assertNotOvulation(drawn[start + 28 - 14],
                           "the formula's day is no longer an ovulation once a day is confirmed")

        // Which is the one the server names instead — the next member of the series.
        assertOvulation(drawn[start + 2 * 28 - 14], "the next occurrence is still drawn")
    }

    /// An anovulatory cycle is the one place the schedule parts company with the calendar on
    /// purpose, so it is pinned rather than left to be discovered. The calendar goes on drawing
    /// the formula's day — the marker is what makes "Нет" revocable, and without it the answer
    /// would be indistinguishable from a day nothing was said about — while the schedule stays
    /// silent about that cycle. §20.2's parity is about which day, not about whether to speak.
    func testAnAnovulatoryCycleStillDrawsTheFormulasDay() {
        let testCase = Case(name: "anovulatory", anchorDaysAgo: 10, openPeriod: false,
                            ovulation: .anovulatory, cycleLength: 28, periodLength: 5,
                            lutealPhase: 14)
        let drawn = states(for: testCase)

        let day = anchor(testCase) + 28 - 14
        assertOvulation(drawn[day], "the day is still marked")

        // The window, and only the window, is what "Нет" takes away.
        XCTAssertNil(drawn[day - 1]?.fertileWindow, "no fertile window the day before")
        XCTAssertNil(drawn[day + 1]?.fertileWindow, "none the day after")
    }

    // MARK: - §20.9, the dictionary

    /// Every key the server can put in a payload's `loc-key` resolves in this bundle.
    ///
    /// iOS draws a key it cannot resolve as the key itself, on the lock screen, so a range the
    /// server widened without a matching string here is not a missing translation but a push
    /// reading `PeriodStart.before_8`. The ranges are the server's
    /// `services/notification-messages.js`; §20.11 is why they are frozen.
    func testEveryKeyTheServerCanSendExistsInTheCatalog() {
        let dictionary: [(prefix: String, offsets: ClosedRange<Int>)] = [
            ("PeriodStart", -7...3),
            ("PeriodEnd", -2...2),
            ("Ovulation", -4...(-4)),
        ]

        var missing: [String] = []
        for (prefix, offsets) in dictionary {
            for offset in offsets {
                let suffix = offset < 0 ? "before_\(-offset)" : offset > 0 ? "after_\(offset)" : "today"
                for key in ["\(prefix).\(suffix)", "\(prefix).\(suffix).named"] where catalog[key] == nil {
                    missing.append(key)
                }
            }
        }
        XCTAssertEqual(missing.sorted(), [], "Keys the server can send with nothing behind them")
    }

    /// And nothing beyond them, because an unused key is a widened range nobody carried through
    /// to the server — the same drift from the other end.
    func testTheCatalogCarriesNoKeyTheServerCannotSend() {
        let expected = 2 * (11 + 5 + 1)
        let actual = catalog.keys.filter { key in
            ["PeriodStart.", "PeriodEnd.", "Ovulation."].contains { key.hasPrefix($0) }
        }
        XCTAssertEqual(actual.count, expected,
                       "§20.9 counts 17 × 2; the catalog has \(actual.count): \(actual.sorted())")
    }

    // MARK: - Driving the calendar

    private func anchor(_ testCase: Case) -> Daystamp {
        Self.today - testCase.anchorDaysAgo
    }

    /// What the calendar actually draws — `computeDayDisplayStates` itself, not a helper that
    /// agrees with it. The loaded range is opened wide enough to hold the whole series, since a
    /// day outside it is simply not drawn and would fail every assertion for the wrong reason.
    private func states(for testCase: Case) -> [Daystamp: DayDisplayState] {
        let start = anchor(testCase)
        var state = CalendarState()
        state.todayDayStamp = Self.today
        state.loadedRange = (start - 400)...(start + 10 * testCase.cycleLength)
        state.cycles = [
            CycleRecord(startDay: start,
                        periodLength: testCase.openPeriod ? 0 : testCase.periodLength,
                        ovulation: testCase.ovulation)
        ]

        let settings = ResolvedCycleSettings(UserSettings.CycleSettings(
            defaultLength: testCase.cycleLength,
            defaultPeriodLength: testCase.periodLength,
            lutealPhaseLength: testCase.lutealPhase,
            autoConfirmPreviousCycle: nil
        ))

        // The case table is written in the numbers the server was given, so a case whose
        // settings this build would clamp would be comparing two different rules (see the
        // divergence noted in SYNC.md §20.11).
        XCTAssertEqual(settings.cycleLength, testCase.cycleLength, "\(testCase.name): cycle length")
        XCTAssertEqual(settings.periodLength, testCase.periodLength, "\(testCase.name): period length")
        XCTAssertEqual(settings.lutealPhaseLength, testCase.lutealPhase, "\(testCase.name): luteal phase")

        return computeDayDisplayStates(state, cycleSettings: settings)
    }

    // MARK: - Reading a day back

    private func assertPeriod(_ state: DayDisplayState?, caps: [SegmentPosition], _ what: String,
                              file: StaticString = #filePath, line: UInt = #line) {
        guard case .period(let position, _)? = state?.cyclePhase else {
            return XCTFail("\(what): no period drawn", file: file, line: line)
        }
        XCTAssertTrue(caps.contains(position),
                      "\(what): drawn as .\(position), expected one of \(caps)",
                      file: file, line: line)
    }

    private func assertOvulation(_ state: DayDisplayState?, _ what: String,
                                 file: StaticString = #filePath, line: UInt = #line) {
        guard let window = state?.fertileWindow else {
            return XCTFail("\(what): no fertile window drawn", file: file, line: line)
        }
        guard case .ovulation = window.phase else {
            return XCTFail("\(what): drawn as .\(window.phase), not an ovulation",
                           file: file, line: line)
        }
    }

    private func assertNotOvulation(_ state: DayDisplayState?, _ what: String,
                                    file: StaticString = #filePath, line: UInt = #line) {
        guard let window = state?.fertileWindow else { return }
        if case .ovulation = window.phase {
            XCTFail("\(what): still drawn as an ovulation", file: file, line: line)
        }
    }

    // MARK: - Catalog

    /// Read from the source tree for the reason `StringCatalogTests` gives: `.xcstrings` is
    /// compiled on the way into the app, and it is the key list being checked, not the lookup.
    private var catalog: [String: [String: Any]] {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("RedCalendar-Female/Localizable.xcstrings")
        let data = try! Data(contentsOf: url)
        let root = try! JSONSerialization.jsonObject(with: data) as! [String: Any]
        return root["strings"] as! [String: [String: Any]]
    }
}
